"""The lab checker of a LearnSome.tech labs repository (run it through ./check).

It runs a lab the way the site's lab sandbox does (workers/labs/run_lab.py on the platform): the starter
files copied into a scratch directory that is the program's working directory and HOME, TMPDIR in a
scratch directory of its own, LANG=C.UTF-8 and TZ=UTC, input.txt on stdin, a 10 second limit and 256 KiB
of output per stream. The output is graded with the site's own comparison rules (grading.py).
Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
"""
import hashlib
import json
import os
import re
import selectors
import shutil
import shlex
import signal
import subprocess
import sys
import tempfile
import time
import urllib.request

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from grading import grade_output  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(ROOT, '.learnsome', 'course.json'), encoding='utf-8') as _f:
    COURSE = json.load(_f)
TIMEOUT_S = COURSE['limits']['timeoutSeconds']
OUTPUT_CAP = COURSE['limits']['outputBytes']
LAB_FILES = {'README.md', 'check.json', 'expected.txt', 'starter'}
MODES = {'graded', 'run', 'checker', 'read-along'}
COLOR = sys.stdout.isatty() and not os.environ.get('NO_COLOR')


def paint(code, text):
    return f'\x1b[{code}m{text}\x1b[0m' if COLOR else text


STATUS = {
    'PASS': paint('32', 'PASS'), 'FAIL': paint('31', 'FAIL'), 'RAN': paint('36', 'RAN '), 'SKIP': paint('33', 'SKIP'),
    'NO TOOL': paint('35', 'NO TOOL'),
}

# ---------- labs ----------


def read_json(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def manifest():
    return read_json(os.path.join(ROOT, '.learnsome', 'labs.json'))


def load_lab(entry):
    d = os.path.join(ROOT, entry['dir'])
    lab = read_json(os.path.join(d, 'check.json'))
    lab['dir'] = d
    lab['relDir'] = entry['dir']
    return lab


def select(names):
    """Labs named on the command line: a lab id (m01l01-02), a lesson id (m01l01) or a path in a lab."""
    entries = manifest()
    picked = {}
    for name in names:
        rel = os.path.relpath(os.path.abspath(name), ROOT).replace(os.sep, '/')
        found = [e for e in entries if e['lab'] == name or e['lesson'] == name or rel == e['dir'] or rel.startswith(e['dir'] + '/')]
        if not found:
            print(f'check: no lab called {name} (./check --list shows them)', file=sys.stderr)
            sys.exit(2)
        for e in found:
            picked.setdefault(e['dir'], e)
    return list(picked.values())


# ---------- tools ----------

SEARCH_PATH = os.pathsep.join([os.path.join(ROOT, 'node_modules', '.bin'), os.environ.get('PATH', '')])


def which(tool):
    return shutil.which(tool, path=SEARCH_PATH)


def missing_tools(lab):
    return [t for t in lab.get('requires', []) if not which(t)]


_go_cache = None


def go_env():
    global _go_cache
    if _go_cache is None:
        _go_cache = os.environ.get('GOCACHE', '')
        if not _go_cache:
            try:
                out = subprocess.run(['go', 'env', 'GOCACHE'], capture_output=True, text=True, env={**os.environ, 'PATH': SEARCH_PATH})
                _go_cache = out.stdout.strip() if out.returncode == 0 else ''
            except OSError:
                _go_cache = ''
    env = {'GOTOOLCHAIN': 'local', 'GOPROXY': 'off', 'GOSUMDB': 'off', 'CGO_ENABLED': '0', 'GOFLAGS': '-buildvcs=false'}
    if _go_cache:
        env['GOCACHE'] = _go_cache
    return env


def kube_schemas():
    """The Kubernetes schemas the site validates against: fetched once, checked against their SHA-256 sums."""
    k8s = COURSE['kubeconform']
    d = os.environ.get('LEARNSOME_K8S_SCHEMAS') or os.path.join(ROOT, '.learnsome', 'cache', 'k8s-schemas')
    os.makedirs(d, exist_ok=True)
    for digest, name in k8s['schemas']:
        path = os.path.join(d, name)

        def ok():
            if not os.path.isfile(path):
                return False
            with open(path, 'rb') as f:
                return hashlib.sha256(f.read()).hexdigest() == digest

        if ok():
            continue
        with urllib.request.urlopen(f"{k8s['url']}/{name}", timeout=30) as resp, open(path, 'wb') as f:
            f.write(resp.read())
        if not ok():
            raise RuntimeError(f'could not fetch the Kubernetes schema {name}')
    return d


TERRAFORM = 'if ls ./*.tf >/dev/null 2>&1; then terraform init -input=false -no-color >/dev/null 2>&1; fi; exec sh "$1"'
TERRAFORM_VALIDATE = (
    'out=$(terraform init -backend=false -input=false -no-color 2>&1) || { printf "%s\\n" "$out"; exit 1; }; '
    'exec terraform validate -no-color'
)
SQL_WITH_FIXTURES = 'db=$1; shift; for f in "$@"; do sqlite3 "$db" < "$f"; done; exec sqlite3 -header -column "$db"'
NODE_TS = ['node', '--experimental-transform-types', '--disable-warning=ExperimentalWarning']
ANSIBLE_ENV = {'ANSIBLE_NOCOLOR': '1', 'ANSIBLE_LOCALHOST_WARNING': 'False', 'ANSIBLE_DEPRECATION_WARNINGS': 'False'}


def terraform_env():
    env = {'CHECKPOINT_DISABLE': '1', 'TF_IN_AUTOMATION': '1', 'GOMAXPROCS': '2'}
    for c in ('init', 'plan', 'apply', 'destroy', 'validate', 'refresh', 'output', 'show', 'import', 'fmt', 'test', 'get'):
        env[f'TF_CLI_ARGS_{c}'] = '-no-color'
    if os.path.exists(COURSE['terraformMirror']):
        env['TF_CLI_CONFIG_FILE'] = COURSE['terraformMirror']
    return env


def command_for(lab, home, tmp):
    """argv, whether the program goes to stdin, and extra environment: run_lab.py's command_for()."""
    f = lab['main']
    r = lab['runner']
    direct = {
        'python': ['python3', f],
        'python-repl': ['python3', os.path.join(ROOT, '.learnsome', 'repl_session.py'), f],
        'bash': ['bash', f],
        'node': ['node', f],
        'node-ts': [*NODE_TS, f],
        'tsx': ['tsx', f],
        # The command line the course recorded beside the listing: run.sh, else command.txt.
        'recorded': ['bash', 'run.sh' if os.path.isfile(os.path.join(home, 'run.sh')) else 'command.txt'],
        'hadolint': ['hadolint', '--no-color', '--failure-threshold', 'error', f],
        'actionlint': ['actionlint', '-no-color', '-shellcheck=', '-pyflakes=', f],
        'yamllint': ['yamllint', '-d', 'relaxed', '-f', 'standard', f],
    }
    if r in direct:
        return direct[r], False, {}
    if r == 'kubeconform':
        schemas = kube_schemas()
        return ['kubeconform', '-strict', '-summary', '-output', 'text', '-ignore-missing-schemas',
                '-schema-location', schemas + '/{{.ResourceKind}}{{.KindSuffix}}.json', f], False, {}
    if r == 'ansible-syntax':
        return ['ansible-playbook', '--syntax-check', '-i', 'localhost,', '-c', 'local', f], False, dict(ANSIBLE_ENV)
    if r == 'terraform-validate':
        return ['sh', '-c', TERRAFORM_VALIDATE], False, terraform_env()
    if r == 'pytest':
        return ['python3', '-m', 'pytest', *pytest_args(home, f)], False, {'COLUMNS': '80'}
    if r == 'csharp':
        # The assembly build_csharp() builds (it runs first), run as the site runs it.
        return ['dotnet', 'exec', csharp_assembly(home)], False, {
            **DOTNET_ENV, 'DOTNET_CLI_HOME': tmp, 'NUGET_PACKAGES': os.path.join(tmp, 'nuget')}
    if r == 'java':
        return ['java', f'-Djava.io.tmpdir={tmp}', f], False, {}
    if r == 'go':
        return ['go', 'run', '.' if os.path.isfile(os.path.join(home, 'go.mod')) else f], False, go_env()
    if r == 'sqlite':
        fixtures = sorted(n for n in os.listdir(home)
                          if n.lower().endswith('.sql') and n != f and os.path.isfile(os.path.join(home, n)))
        if not fixtures:
            return ['sqlite3', '-header', '-column', ':memory:'], True, {}
        return ['bash', '-c', SQL_WITH_FIXTURES, 'seed', os.path.splitext(fixtures[0])[0] + '.db', *fixtures], True, {}
    if r == 'terraform':
        script = 'cmd.sh' if os.path.isfile(os.path.join(home, 'cmd.sh')) else f
        return ['sh', '-c', TERRAFORM, 'terraform-lab', script], False, {**terraform_env(), **ANSIBLE_ENV}
    raise RuntimeError(f'no runner {r}')


# Variables passed through from your shell, beyond the sandbox's own (toolchains that find themselves by them).
PASS_THROUGH = ('JAVA_HOME', 'GOROOT', 'SSL_CERT_FILE', 'SYSTEMROOT', 'DOTNET_ROOT')
DOTNET_ENV = {'DOTNET_CLI_TELEMETRY_OPTOUT': '1', 'DOTNET_NOLOGO': '1', 'DOTNET_SKIP_FIRST_TIME_EXPERIENCE': '1',
              'DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE': '1'}
# Where the site's output shows a C# program's own assembly (run_lab.py CSHARP_OUT_SHOWN).
CSHARP_OUT_SHOWN = '/work/bin/Debug/net10.0'


def csharp_dirs(home):
    """The run's build directory (a copy of the sources) and its output directory, beside the program's."""
    build = os.path.join(os.path.dirname(home), 'build')
    return build, os.path.join(build, 'out')


def csharp_assembly(home):
    project = next((n for n in sorted(os.listdir(home)) if n.endswith('.csproj')), 'snippet.csproj')
    return os.path.join(csharp_dirs(home)[1], os.path.splitext(project)[0] + '.dll')


def build_csharp(home, env):
    """`dotnet build` of the lab's project, from a copy of it, before the timed run (the site compiles within its
    limit with a warm compiler; a cold local build would not fit). Its warnings and errors come first, as
    `dotnet run` shows them. Returns (ok, output)."""
    build, out = csharp_dirs(home)
    shutil.copytree(home, build)
    try:
        proc = subprocess.run(['dotnet', 'build', '--nologo', '-v', 'quiet', '-clp:NoSummary', '-o', out], cwd=build,
                              env=env, stdin=subprocess.DEVNULL, capture_output=True, timeout=300)
    except subprocess.TimeoutExpired:
        return False, 'dotnet build did not finish in 5 minutes\n'
    text = (proc.stdout + proc.stderr).decode('utf-8', 'replace')
    # What the site shows before the program's output is the compiler's (csc's) diagnostics only: MSBuild's own
    # notices (workload checks, restore) are left out, and so is the project suffix MSBuild adds to each line.
    lines = [re.sub(r' \[[^\]]*\.csproj\]$', '', l) for l in text.splitlines() if re.search(r': (?:error|warning) [A-Z]+[0-9]+:', l)]
    if proc.returncode != 0 and not lines:
        lines = text.splitlines()
    text = ''.join(f'{l}\n' for l in dict.fromkeys(lines))
    # Names as the site shows them: the sources in the program's directory.
    text = re.sub(rf'(?<![\w./-]){re.escape(build)}(?![\w.-])', home, text)
    return proc.returncode == 0, text


class Capped:
    def __init__(self):
        self.chunks = []
        self.size = 0
        self.truncated = False

    def push(self, chunk):
        room = OUTPUT_CAP - self.size
        if len(chunk) > room:
            chunk = chunk[:room]
            self.truncated = True
        if chunk:
            self.chunks.append(chunk)
            self.size += len(chunk)

    def text(self):
        return b''.join(self.chunks).decode('utf-8', 'replace')


def pytest_args(home, file_name):
    """The arguments of the lab's recorded pytest command (command.txt), else just the test file."""
    try:
        with open(os.path.join(home, 'command.txt'), encoding='utf-8') as f:
            words = shlex.split(f.read())
    except (OSError, ValueError):
        words = []
    return words[1:] if words[:1] == ['pytest'] and len(words) > 1 else [file_name]


def run_capped(argv, cwd, env, stdin_bytes, merge=False):
    """`merge`: stderr goes to stdout (2>&1), in the order it was written, as for labs recorded that way."""
    started = time.monotonic()
    with tempfile.TemporaryFile() as stdin_file:
        stdin_file.write(stdin_bytes)
        stdin_file.seek(0)
        try:
            proc = subprocess.Popen(argv, cwd=cwd, env=env, stdin=stdin_file, stdout=subprocess.PIPE,
                                    stderr=subprocess.STDOUT if merge else subprocess.PIPE,
                                    start_new_session=True, close_fds=True)
        except OSError as err:
            return {'exitCode': 127, 'stdout': '', 'stderr': f'{argv[0]}: {err}\n', 'durationMs': 0,
                    'timedOut': False, 'truncated': False}

    def kill():
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except OSError:
            pass

    outputs = {proc.stdout: Capped()}
    if proc.stderr:
        outputs[proc.stderr] = Capped()
    sel = selectors.DefaultSelector()
    for pipe in outputs:
        os.set_blocking(pipe.fileno(), False)
        sel.register(pipe, selectors.EVENT_READ)
    deadline = started + TIMEOUT_S
    timed_out = False
    ended_at = None
    stopped_at = None
    while True:
        now = time.monotonic()
        if ended_at is None and proc.poll() is not None:
            ended_at = now
            kill()  # anything the program left running goes with it
        if ended_at is None and not timed_out and now >= deadline:
            timed_out = True
            stopped_at = stopped_at or now
            kill()
        if ended_at is not None and (not sel.get_map() or now - ended_at > 2):
            break
        if timed_out and ended_at is None and now >= deadline + 5:
            break
        if not sel.get_map():
            time.sleep(0.05)
            continue
        for key, _ in sel.select(timeout=0.05):
            try:
                chunk = os.read(key.fileobj.fileno(), 65536)
            except BlockingIOError:
                continue
            if not chunk:
                sel.unregister(key.fileobj)
                key.fileobj.close()
                continue
            buf = outputs[key.fileobj]
            buf.push(chunk)
            if buf.truncated and ended_at is None:
                stopped_at = stopped_at or time.monotonic()
                kill()
    kill()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        pass
    for pipe in outputs:
        if not pipe.closed:
            pipe.close()
    ends = [t for t in (stopped_at, ended_at, time.monotonic()) if t is not None]
    code = proc.returncode
    out = outputs[proc.stdout]
    err = outputs[proc.stderr] if proc.stderr else Capped()
    return {
        'exitCode': 137 if code is None else 128 - code if code < 0 else code,
        'stdout': out.text(),
        'stderr': err.text(),
        'durationMs': round((min(ends) - started) * 1000),
        'timedOut': timed_out,
        'truncated': out.truncated or err.truncated,
    }


def execute(lab):
    """Copies the lab's files into a scratch directory, runs it and returns run_lab.py's result shape."""
    base = os.path.realpath(tempfile.mkdtemp(prefix='learnsome-lab-'))
    home = os.path.join(base, 'work')  # the program's directory, named as on the site
    tmp = os.path.join(base, 'tmp')
    os.mkdir(home)
    os.mkdir(tmp)
    try:
        copies = [(os.path.join(lab['dir'], 'starter', n), n) for n in lab['files']]
        copies += [(os.path.join(ROOT, s['from']), s['path']) for s in lab.get('shared', [])]
        for src, name in copies:
            target = os.path.join(home, name)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            shutil.copyfile(src, target)
            os.chmod(target, 0o644)  # as the sandbox writes them: not executable
        if lab['runner'] in ('node', 'node-ts', 'tsx') and not os.path.lexists(os.path.join(home, 'node_modules')) \
                and os.path.isdir(os.path.join(ROOT, 'node_modules')):
            os.symlink(os.path.join(ROOT, 'node_modules'), os.path.join(home, 'node_modules'))
        if lab['runner'] == 'tsx' and not os.path.lexists(os.path.join(home, 'package.json')):
            with open(os.path.join(base, 'package.json'), 'w') as f:
                f.write('{"type": "module"}\n')
        argv, code_on_stdin, extra_env = command_for(lab, home, tmp)
        if code_on_stdin:
            stdin_path = os.path.join(home, lab['main'])
        elif lab.get('stdin'):
            stdin_path = os.path.join(lab['dir'], 'starter', lab['stdin'])
        else:
            stdin_path = None
        stdin_bytes = b''
        if stdin_path:
            with open(stdin_path, 'rb') as f:
                stdin_bytes = f.read()
        env = {'LANG': 'C.UTF-8', 'TZ': 'UTC', 'HOME': home, 'PATH': SEARCH_PATH, 'TMPDIR': tmp, **extra_env}
        for key in PASS_THROUGH:
            if os.environ.get(key) and key not in env:
                env[key] = os.environ[key]
        prefix = ''
        if lab['runner'] == 'csharp':
            ok, prefix = build_csharp(home, env)
            if not ok:
                result = {'exitCode': 1, 'stdout': prefix, 'stderr': '', 'durationMs': 0, 'timedOut': False, 'truncated': False}
        if lab['runner'] != 'csharp' or ok:
            result = run_capped(argv, home, env, stdin_bytes, merge=lab.get('mergeStderr') is True)
            result['stdout'] = prefix + result['stdout']
        # Paths as the site shows them: the program's directory as /work (relative before a file name), its
        # scratch space as /tmp, and a C# program's own assembly directory as the SDK's output directory.
        for key in ('stdout', 'stderr'):
            text = result[key]
            if lab['runner'] == 'csharp':
                text = re.sub(rf'(?<![\w./-]){re.escape(csharp_dirs(home)[1])}(?![\w.-])', CSHARP_OUT_SHOWN, text)
            text = re.sub(rf'(?<![\w./-]){re.escape(home)}/', '', text)
            text = re.sub(rf'(?<![\w./-]){re.escape(home)}(?![\w.-])', '/work', text)
            result[key] = re.sub(rf'(?<![\w./-]){re.escape(tmp)}(?![\w.-])', '/tmp', text)
        return result
    finally:
        shutil.rmtree(base, ignore_errors=True)


# ---------- checking ----------


def show_diff(diff):
    for d in diff[:20]:
        print(f"    line {d['line']}:")
        print(f"      expected: {'(nothing)' if d['expected'] is None else json.dumps(d['expected'], ensure_ascii=False)}")
        print(f"      got:      {'(nothing)' if d['actual'] is None else json.dumps(d['actual'], ensure_ascii=False)}")
    if len(diff) > 20:
        print(f'    … {len(diff) - 20} more differing lines')


def show_output(result):
    text = result['stdout']
    if result['stderr']:
        text += ('\n' if text and not text.endswith('\n') else '') + result['stderr']
    if not text:
        return
    for line in text[:-1].split('\n') if text.endswith('\n') else text.split('\n'):
        print(f'    | {line}')


def check_lab(lab, verbose):
    """Runs one lab: 'pass', 'fail', 'ran', 'skip' or 'notool'."""
    label = f"{lab['lab']}  {lab['title']}"
    if lab['mode'] == 'read-along':
        print(f"{STATUS['SKIP']}  {label}\n    read along: {lab['note']}")
        return 'skip'
    missing = missing_tools(lab)
    if missing:
        print(f"{STATUS['NO TOOL']}  {label}\n    needs {', '.join(missing)} on your PATH (the dev container has them)")
        return 'notool'
    result = execute(lab)
    limits = [x for x in (result['timedOut'] and f'stopped after {TIMEOUT_S} s',
                          result['truncated'] and 'output over the size limit') if x]
    limit_note = f" ({', '.join(limits)})" if limits else ''
    if lab['mode'] == 'checker':
        ok = result['exitCode'] == 0 and not result['timedOut']
        print(f"{STATUS['PASS'] if ok else STATUS['FAIL']}  {label}\n    {lab['command']}: exit {result['exitCode']}{limit_note}")
        if not ok or verbose:
            show_output(result)
        return 'pass' if ok else 'fail'
    if lab['mode'] == 'run':
        print(f"{STATUS['RAN']}  {label}\n    {lab['command']}: exit {result['exitCode']}{limit_note}; not graded: {lab['note']}")
        if verbose:
            show_output(result)
        return 'ran'
    with open(os.path.join(lab['dir'], lab['expected']), encoding='utf-8') as f:
        expected = f.read()
    graded = grade_output(result['stdout'], result['stderr'], expected, lab['grading'])
    passed = graded['passed'] and not result['timedOut'] and not result['truncated']
    print(f"{STATUS['PASS'] if passed else STATUS['FAIL']}  {label}")
    if not passed:
        if limits:
            print(f"    {', '.join(limits)}")
        if graded['diff']:
            print(f"    output differs from {lab['relDir']}/{lab['expected']}:")
            show_diff(graded['diff'])
    elif verbose:
        show_output(result)
    return 'pass' if passed else 'fail'


# ---------- lint (what CI runs) ----------


def list_files(d):
    out = []
    for root, _dirs, names in os.walk(d):
        for n in names:
            out.append(os.path.relpath(os.path.join(root, n), d).replace(os.sep, '/'))
    return out


def lint_structure(problems):
    entries = manifest()
    known = {e['dir'] for e in entries}
    lesson_dirs = sorted({os.path.dirname(e['dir']) for e in entries})
    for lesson_dir in lesson_dirs:
        if not os.path.isfile(os.path.join(ROOT, lesson_dir, 'README.md')):
            problems.append(f'{lesson_dir}: no README.md')
        for name in sorted(os.listdir(os.path.join(ROOT, lesson_dir))):
            rel = f'{lesson_dir}/{name}'
            if name != 'README.md' and rel not in known:
                problems.append(f'{rel}: not a lab of this course')
            elif rel in known and not os.path.isdir(os.path.join(ROOT, rel)):
                problems.append(f'{rel}: not a directory')
    for name in sorted(os.listdir(os.path.join(ROOT, 'labs'))):
        if f'labs/{name}' not in lesson_dirs:
            problems.append(f'labs/{name}: not a lesson of this course')
    for entry in entries:
        d = os.path.join(ROOT, entry['dir'])
        where = entry['dir']
        if not os.path.isfile(os.path.join(d, 'README.md')):
            problems.append(f'{where}: no README.md')
        try:
            lab = load_lab(entry)
        except FileNotFoundError:
            problems.append(f'{where}/check.json: missing')
            continue
        except ValueError as err:
            problems.append(f'{where}/check.json: {err}')
            continue
        if lab.get('lab') != entry['lab']:
            problems.append(f"{where}/check.json: lab is {lab.get('lab')}, expected {entry['lab']}")
        if lab.get('mode') not in MODES:
            problems.append(f"{where}/check.json: unknown mode {lab.get('mode')}")
        if lab.get('mode') != 'read-along' and not lab.get('runner'):
            problems.append(f'{where}/check.json: no runner')
        if lab.get('mode') in ('read-along', 'run') and not lab.get('note'):
            problems.append(f'{where}/check.json: no note')
        for name in sorted(os.listdir(d)):
            if name not in LAB_FILES:
                problems.append(f'{where}/{name}: not part of the lab')
        if lab.get('mode') == 'graded':
            if not lab.get('expected') or not os.path.isfile(os.path.join(d, lab['expected'])):
                problems.append(f'{where}: graded but has no expected output')
            if not lab.get('grading'):
                problems.append(f'{where}/check.json: graded without a grading rule')
        elif os.path.exists(os.path.join(d, 'expected.txt')):
            problems.append(f'{where}/expected.txt: only graded labs have expected output')
        files = set(lab.get('files', []))
        if lab.get('main') not in files:
            problems.append(f"{where}/check.json: main file {lab.get('main')} is not listed")
        for name in sorted(files):
            if not os.path.isfile(os.path.join(d, 'starter', name)):
                problems.append(f'{where}/starter/{name}: missing')
        starter = os.path.join(d, 'starter')
        for name in sorted(list_files(starter) if os.path.isdir(starter) else []):
            if name not in files:
                problems.append(f'{where}/starter/{name}: not listed in check.json')
        if lab.get('stdin') and lab['stdin'] not in files:
            problems.append(f"{where}/check.json: stdin file {lab['stdin']} is not a starter file")
        for s in lab.get('shared', []):
            if not os.path.isfile(os.path.join(ROOT, s['from'])):
                problems.append(f"{where}: shared file {s['from']} missing")


LANGUAGE_FILES = {
    'python': ('.py',), 'pytest': ('.py',), 'bash': ('.sh',), 'recorded': ('.sh',), 'go': ('.go',), 'java': ('.java',),
    'node': ('.js', '.mjs', '.cjs'),
}


def _tail(text, n=4):
    return '\n'.join(text.strip().split('\n')[-n:])


def lint_syntax(problems, missing):
    for entry in manifest():
        lab = load_lab(entry)
        if lab['mode'] == 'read-along' or lab.get('syntax') is False:
            continue
        if lab['runner'] == 'csharp':
            if not which('dotnet'):
                missing.add('dotnet')
                continue
            base = tempfile.mkdtemp(prefix='learnsome-dotnet-')
            home = os.path.join(base, 'home')
            try:
                for name in lab['files']:
                    target = os.path.join(home, name)
                    os.makedirs(os.path.dirname(target), exist_ok=True)
                    shutil.copyfile(os.path.join(lab['dir'], 'starter', name), target)
                ok, out = build_csharp(home, {**os.environ, 'PATH': SEARCH_PATH, **DOTNET_ENV,
                                              'DOTNET_CLI_HOME': base, 'NUGET_PACKAGES': os.path.join(base, 'nuget')})
            finally:
                shutil.rmtree(base, ignore_errors=True)
            if not ok:
                problems.append(f"{lab['relDir']}/starter: does not compile\n" + '\n'.join(out.strip().split('\n')[:6]))
            continue
        exts = LANGUAGE_FILES.get(lab['runner'], ())
        # A recorded shell session is bash, whatever its extension.
        files = [f for f in lab['files'] if (f == lab['main'] and lab['runner'] == 'bash') or os.path.splitext(f)[1] in exts]
        java_files = []
        for name in files:
            path = os.path.join(lab['dir'], 'starter', name)
            where = f"{lab['relDir']}/starter/{name}"
            ext = os.path.splitext(name)[1]
            if ext == '.java':
                java_files.append(path)
                continue
            if lab['runner'] in ('python', 'pytest') and ext == '.py':
                import ast
                try:
                    with open(path, 'rb') as f:
                        ast.parse(f.read(), path)
                except SyntaxError as err:
                    problems.append(f'{where}: does not parse\n{err}')
                continue
            if lab['runner'] in ('bash', 'recorded') or ext == '.sh':
                tool, args = 'bash', ['-n', path]
            elif ext == '.go':
                tool, args = 'gofmt', ['-e', '-l', path]
            elif ext in ('.js', '.mjs', '.cjs'):
                tool, args = 'node', ['--check', path]
            else:
                continue
            if not which(tool):
                missing.add(tool)
                continue
            res = subprocess.run([tool, *args], capture_output=True, text=True, env={**os.environ, 'PATH': SEARCH_PATH})
            if res.returncode != 0:
                problems.append(f'{where}: does not parse\n{_tail(res.stderr or res.stdout)}')
        if java_files:
            if not which('javac'):
                missing.add('javac')
                continue
            # `java File.java` compiles that one file, whatever its public type is called; javac wants the file
            # named after it, so the check compiles a copy under that name.
            with open(os.path.join(lab['dir'], 'starter', lab['main']), encoding='utf-8') as f:
                source = f.read()
            m = PUBLIC_TYPE.search(source)
            out = tempfile.mkdtemp(prefix='learnsome-javac-')
            copy = os.path.join(out, f'{m.group(1) if m else os.path.splitext(lab["main"])[0]}.java')
            with open(copy, 'w', encoding='utf-8') as f:
                f.write(source)
            res = subprocess.run(['javac', '-proc:none', '-nowarn', '-d', out, copy], capture_output=True, text=True)
            shutil.rmtree(out, ignore_errors=True)
            if res.returncode != 0:
                problems.append(f"{lab['relDir']}/starter/{lab['main']}: does not compile\n" + '\n'.join(res.stderr.strip().split('\n')[:6]))


PUBLIC_TYPE = re.compile(r'^\s*public\s+(?:(?:abstract|final|sealed|non-sealed|static|strictfp)\s+)*(?:class|record|interface|enum|@interface)\s+(\w+)', re.M)


def lint(strict):
    problems = []
    missing = set()
    lint_structure(problems)
    lint_syntax(problems, missing)
    # The checker labs: the starter must pass the site's checker (hadolint, actionlint, kubeconform...).
    checked = 0
    for entry in manifest():
        lab = load_lab(entry)
        if lab['mode'] != 'checker':
            continue
        tools = missing_tools(lab)
        if tools:
            missing.update(tools)
            continue
        result = execute(lab)
        checked += 1
        if result['exitCode'] != 0 or result['timedOut']:
            out = '\n'.join((result['stdout'] + result['stderr']).strip().split('\n')[:6])
            problems.append(f"{lab['relDir']}: {lab['command']} failed (exit {result['exitCode']})\n{out}")
    for p in problems:
        print(f"{STATUS['FAIL']}  {p}")
    if missing:
        print(f"{STATUS['FAIL'] if strict else STATUS['SKIP']}  not checked, missing on PATH: {', '.join(sorted(missing))}")
    summary = f'{len(problems)} problems' if problems else 'structure and syntax OK'
    print(f"{len(manifest())} labs: {summary}{f', {checked} checker labs run' if checked else ''}")
    return 1 if problems or (strict and missing) else 0


# ---------- main ----------

HELP = f"""Usage:
  ./check <lab>...        run labs and compare with the expected output, as the site does
                          (<lab> is a lab id like {COURSE['exampleLab']}, a lesson id, or a path in a lab)
  ./check --all           every lab of the course
  ./check --list          the labs, and how each is checked
  ./check --lint          repository structure, starter syntax and checker labs (what CI runs)
Options: -v / --verbose shows the program's output; --strict (with --lint) fails when a tool is missing."""


def main(args):
    flags = {a for a in args if a.startswith('-')}
    names = [a for a in args if not a.startswith('-')]
    unknown = sorted(flags - {'--all', '--list', '--lint', '--strict', '-v', '--verbose', '-h', '--help'})
    if '-h' in flags or '--help' in flags or unknown or (not names and not flags & {'--all', '--list', '--lint'}):
        if unknown:
            print(f"check: unknown option {' '.join(unknown)}", file=sys.stderr)
        print(HELP)
        return 2 if unknown else 0
    if '--lint' in flags:
        return lint('--strict' in flags)
    if '--list' in flags:
        for entry in manifest():
            lab = load_lab(entry)
            print(f"{lab['lab']:<14} {lab['mode']:<10} {lab.get('command') or ''}")
        return 0
    entries = manifest() if '--all' in flags else select(names)
    verbose = bool(flags & {'-v', '--verbose'}) or len(entries) == 1
    tally = {'pass': 0, 'fail': 0, 'ran': 0, 'skip': 0, 'notool': 0}
    for entry in entries:
        tally[check_lab(load_lab(entry), verbose)] += 1
    if len(entries) > 1:
        tail = f", {tally['notool']} not run (missing tool)" if tally['notool'] else ''
        print(f"\n{tally['pass']} passed, {tally['fail']} failed, {tally['ran']} ran without grading, {tally['skip']} read along{tail}")
    return 1 if tally['fail'] else 2 if tally['notool'] else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
