"""Output grading of LearnSome.tech labs: a line-for-line port of the platform grader
(workers/labs/src/grading.js), so a pass here is a pass on the site. JavaScript's regular expression
semantics are kept where they differ from Python's: `\\s` and trimming use JavaScript's whitespace set,
`\\d` and `\\w` are ASCII, `.` stops at every line terminator, and `$` is the end of the text.

Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
"""
import math
import re

# JavaScript's WhiteSpace and LineTerminator characters: what `\s` matches and String#trim removes.
JS_SPACE = '\t\n\x0b\x0c\r \xa0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000\ufeff'
_S = '[' + re.escape(JS_SPACE) + ']'
_NS = '[^' + re.escape(JS_SPACE) + ']'
_DOT = '[^\n\r\u2028\u2029]'
MAX_DIFF = 200


def _trim_end(s):
    return s.rstrip(JS_SPACE)


def _trim(s):
    return s.strip(JS_SPACE)


def _newlines(text):
    return re.sub(r'\r\n?', '\n', text)


def normalize_lines(text):
    """Contract comparison: per-line trailing whitespace trimmed, trailing blank lines ignored."""
    joined = '\n'.join(_trim_end(line) for line in _newlines(text).split('\n'))
    return joined.rstrip('\n').split('\n')


_TRACEBACK = re.compile(r'^Traceback \(most recent call last\):' + _S + r'*\Z')
_FILE_LINE = re.compile('^' + _S + r'+File "' + _DOT + r'*", line [0-9]+')
_CARET = re.compile('^' + _S + r'*[\^~]+' + _S + r'*\Z')
_SOURCE = re.compile('^' + _S + '{4}' + _NS)


def course_normalize(text):
    """Traceback scaffolding (File/source/caret lines) and blank lines set aside."""
    out = []
    for line in _newlines(text).split('\n'):
        if _TRACEBACK.search(line) or _FILE_LINE.search(line) or _CARET.search(line) or _SOURCE.search(line):
            continue
        line = _trim_end(line)
        if line != '':
            out.append(line)
    return '\n'.join(out)


def _diff(actual, expected):
    diff = []
    for i in range(max(len(actual), len(expected))):
        if len(diff) >= MAX_DIFF:
            break
        a = actual[i] if i < len(actual) else None
        e = expected[i] if i < len(expected) else None
        if a != e:
            diff.append({'line': i + 1, 'expected': e, 'actual': a})
    return diff


def line_diff(actual_text, expected_text):
    return _diff(normalize_lines(actual_text), normalize_lines(expected_text))


# sqlite3 builds differ in column alignment and float printing, so SQL result sets are compared cell by cell.
_SQL_ERROR = re.compile(r'^(?:Runtime error|Error|Parse error)(?: near line [0-9]+)?: (' + _DOT + r'*?)(?: \([0-9]+\))?\Z')


def _sql_error(line):
    line = _SQL_ERROR.sub(lambda m: 'ERROR: ' + m.group(1), line, count=1)
    return _trim(re.sub(_S + '+', ' ', line))


def _sql_cells(line):
    return [c for c in re.split(_S + '{2,}', _trim(line)) if c]


_DECIMAL = re.compile(r'[+-]?(?:[0-9]+\.?[0-9]*|\.[0-9]+)(?:[eE][+-]?[0-9]+)?\Z')
_RADIX = {'x': (16, '0123456789abcdefABCDEF'), 'o': (8, '01234567'), 'b': (2, '01')}


def js_number(text):
    """JavaScript's Number(text) for a string."""
    s = _trim(text)
    if s == '':
        return 0.0
    if _DECIMAL.match(s):
        return float(s)
    if s in ('Infinity', '+Infinity'):
        return math.inf
    if s == '-Infinity':
        return -math.inf
    if len(s) > 2 and s[0] == '0' and s[1].lower() in _RADIX:
        base, digits = _RADIX[s[1].lower()]
        if all(ch in digits for ch in s[2:]):
            return float(int(s[2:], base))
    return math.nan


def _sql_cell_equals(a, b):
    if a == b:
        return True
    x = js_number(a)
    y = js_number(b)
    return a != '' and b != '' and not math.isnan(x) and not math.isnan(y) and abs(x - y) < 1e-4


_RULE = re.compile(r'^[- ]+\Z')


def _sql_line_equals(exp, act):
    if exp == act:
        return True
    e = _sql_error(exp)
    if e.startswith('ERROR:') and e == _sql_error(act):
        return True
    if _RULE.match(exp) and _RULE.match(act):
        return True
    ec = _sql_cells(exp)
    ac = _sql_cells(act)
    return len(ec) > 0 and len(ec) == len(ac) and all(_sql_cell_equals(c, ac[i]) for i, c in enumerate(ec))


def _sql_same_output(expected_text, actual_text):
    def clean(t):
        return [line for line in (_trim_end(x) for x in _newlines(t).split('\n')) if _trim(line) != '']

    exp = clean(expected_text)
    act = clean(actual_text)
    return len(exp) == len(act) and all(_sql_line_equals(line, act[i]) for i, line in enumerate(exp))


ANSI = re.compile(r'\x1b\[[0-9;?]*[A-Za-z]')

_ANSIBLE_WARNING_START = re.compile('^' + _S + r'*\[(?:WARNING|DEPRECATION WARNING|NOTICE)\]')
_ANSIBLE_ROW = re.compile(r'^(?:PLAY|TASK|RUNNING HANDLER|HANDLER|ok:|changed:|failed:|fatal:|skipping:|ignoring:|included:|localhost|---|\+\+\+|@@)')
_ANSIBLE_ENVIRONMENTAL = [
    re.compile('^' + _S + r'*\[WARNING\]'),
    re.compile('^' + _S + r'*\[DEPRECATION WARNING\]'),
    re.compile(r'^You are using'),
    re.compile('^' + _S + r'*no action detected in task'),
    re.compile(r'Python interpreter'),
    re.compile('^' + _S + r'*See https://docs\.ansible\.com'),
]


def ansible_normalize(text):
    out = []
    in_warning = False
    for raw in _newlines(text).split('\n'):
        line = ANSI.sub('', raw)
        if _ANSIBLE_WARNING_START.search(line):
            in_warning = True
            continue
        if in_warning:
            if not _ANSIBLE_ROW.search(line):
                continue
            in_warning = False
        if any(r.search(line) for r in _ANSIBLE_ENVIRONMENTAL):
            continue
        collapsed = re.sub(r'\*{2,}', '***', line)
        collapsed = re.sub(r'={3,}', '===', collapsed)
        collapsed = _trim(re.sub(_S + '+', ' ', collapsed))
        if collapsed != '':
            out.append(collapsed)
    return out


_TERRAFORM_NOISE = [re.compile(p) for p in (
    r'^- Finding ',
    r'^- Installing ',
    r'^- Installed ',
    r'^- Using ',
    r'^- Reusing previous version of ',
    r'^- Downloading ',
    r'^Initializing provider plugins\.\.\.\Z',
    r'^Initializing modules\.\.\.\Z',
    r'^Initializing the backend\.\.\.\Z',
    r'^Terraform has created a lock file',
    r'^selections it made above\.',
    r'^so that Terraform can guarantee',
    r'^you run "terraform init" in the future\.',
    r'^Your version of Terraform is out of date',
    r'^is [0-9]+\.[0-9]+\.[0-9]+\. You can update by downloading',
    r'^Terraform used the selected providers to generate the following execution\Z',
    r'^plan\. Resource actions are indicated with the following symbols:\Z',
    r'^Terraform has compared your real infrastructure against your\Z',
    r'^configuration and found no differences, so no changes are needed\.\Z',
    r'^Terraform has compared your real infrastructure against your configuration\Z',
    r'^and found no differences, so no changes are needed\.\Z',
    r'\[[0-9]+s elapsed\]\Z',
    r'^Acquiring state lock\.',
    r'^Releasing state lock\.',
    r'^Stopping operation\.\.\.',
)]

_TERRAFORM_MASKS = [(re.compile(p, re.ASCII), r) for p, r in (
    (r'\[id=[^\]]*\]', '[id=ID]'),
    (r'\bid *= *"[^"]*"', 'id = "ID"'),
    (r'\bafter \d+m?\d+s\b', 'after Ns'),
    (r'\bv\d+\.\d+\.\d+\b', 'vX.Y.Z'),
    (r'\b20\d\d-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z?\b', 'TIMESTAMP'),
    (r'/(?:private/)?(?:var|tmp)/[\w./-]*tfcourse-[\w./-]*', 'WORKDIR'),
    (r'/(?:private/)?var/folders/[\w./+-]+', 'WORKDIR'),
)]


def _terraform_mask(line):
    for pattern, replacement in _TERRAFORM_MASKS:
        line = pattern.sub(lambda _m, r=replacement: r, line)
    return line


def terraform_normalize(text):
    out = []
    for raw in _newlines(text).split('\n'):
        line = _trim_end(ANSI.sub('', raw))
        if line != '' and not any(r.search(line) for r in _TERRAFORM_NOISE):
            out.append(_terraform_mask(line))
    return out



# dotnet-course scripts/output.ts: SDK restore, build and test-platform banners, Kestrel's start-up lines and
# stack-trace frames dropped; times, paths, guids and timestamps masked; blank lines ignored.
def _dn(pattern):
    """A DOTNET_NOISE pattern in JavaScript notation: \\s, \\S, \\d and . as JavaScript means them."""
    out = pattern.replace(r'\S', '\x00NS\x00').replace(r'\s', '\x00S\x00').replace(r'\d', '[0-9]').replace('.*', '\x00DOT\x00*')
    out = out.replace('\x00NS\x00', _NS).replace('\x00S\x00', _S).replace('\x00DOT\x00', _DOT)
    if out.endswith('$'):
        out = out[:-1] + r'\Z'
    return re.compile(out, re.ASCII)


_DOTNET_NOISE = [_dn(p) for p in (
    r'^\s*Determining projects to restore\.{3}\s*$',
    r'^\s*All projects are up-to-date for restore\.\s*$',
    r'^\s*Restored .*$',
    r'^\s*Restore complete.*$',
    r'^\s*Restore succeeded.*$',
    r'^\s*Nothing to do\. None of the projects specified contain packages to restore\.\s*$',
    r'^\s*MSBuild version .*$',
    r'^\s*Welcome to \.NET.*$',
    r'^\s*-{3,}.*$',
    r'^\s*Telemetry\b.*$',
    r'^\s*Learn (?:more|about) .*$',
    r'^\s*Build succeeded(?: in .*)?\.?\s*$',
    r'^\s*Build succeeded with .*$',
    r'^\s*\d+ Warning\(s\)\s*$',
    r'^\s*\d+ Error\(s\)\s*$',
    r'^\s*Time Elapsed .*$',
    r'^\s*Elapsed time: .*$',
    r'^\s*\S+ -> /.*\.(?:dll|exe)\s*$',
    r'^\s*Microsoft \(R\) Test Execution Command Line Tool.*$',
    r'^\s*Copyright \(c\) Microsoft Corporation\..*$',
    r'^\s*Starting test execution, please wait\.{3}\s*$',
    r'^\s*A total of \d+ test files matched the specified pattern\.\s*$',
    r'^\s*VSTest version .*$',
    r'^\s*Test run for .*$',
    r'^\s*Results File: .*$',
    r'^\s*info: Microsoft\.Hosting\.Lifetime.*$',
    r'^\s*Now listening on: .*$',
    r'^\s*Application started\. Press Ctrl\+C to shut down\.\s*$',
    r'^\s*Hosting environment: .*$',
    r'^\s*Content root path: .*$',
    r'^\s+at .+$',
    r'^\s*--- End of stack trace from previous location ---\s*$',
)]
# `.+` in the stack-frame pattern: one or more characters other than line terminators.
_DOTNET_NOISE[-2] = re.compile('^' + _S + '+at ' + _DOT + r'+\Z', re.ASCII)

_DOTNET_UNSTABLE = [(re.compile(p, re.ASCII), r) for p, r in (
    (r'\b[0-9]+(?:[.,][0-9]+)?' + _S + r'?(?:ms|s|sec|secs|seconds|m)\b', 'TIME'),
    (r'(?:/[\w.@+-]+){2,}', 'PATH'),
    (r'[A-Za-z]:\\[\w.\\@+-]+', 'PATH'),
    (r'\b[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\b', 'GUID'),
    (r'\b[0-9]{4}-[0-9]{2}-[0-9]{2}[T ][0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]+)?(?:Z|[+-][0-9]{2}:[0-9]{2})?', 'TIMESTAMP'),
)]


def dotnet_normalize(text):
    out = []
    for raw in _newlines(text).split('\n'):
        line = ANSI.sub('', raw)
        if any(r.search(line) for r in _DOTNET_NOISE):
            continue
        for pattern, replacement in _DOTNET_UNSTABLE:
            line = pattern.sub(lambda _m, r=replacement: r, line)
        line = line.rstrip(JS_SPACE)
        if line != '':
            out.append(line)
    return out

def _rstrip_ws(line):
    """JavaScript's line.replace(/\\s+$/, '')."""
    return line.rstrip(JS_SPACE)


def bash_normalize(text):
    """bash-course: every line compared, inner blank lines included; trailing whitespace and the blank lines
    before the first and after the last line of output set aside."""
    lines = [_rstrip_ws(l) for l in _newlines(text).split('\n')]
    first, last = 0, len(lines)
    while first < last and lines[first] == '':
        first += 1
    while last > first and lines[last - 1] == '':
        last -= 1
    return lines[first:last]


_NQ = "[^" + re.escape(JS_SPACE) + "'\")]"
_GIT_RULES = [(re.compile(p, re.ASCII), r) for p, r in (
    (r'/(?:private/)?(?:var|tmp)/' + _NQ + r'*gitcourse-[A-Za-z0-9]+' + _NQ + '*', '<dir>'),
    (r'/(?:private/)?(?:var|tmp)/[A-Za-z0-9._/-]+', '<dir>'),
)]
_GIT_DATE_LINE = re.compile(r'^((?:Author|Commit)?Date:' + _S + '+)' + _DOT + r'*\Z')
_GIT_REST = [(re.compile(p, re.ASCII), r) for p, r in (
    (r'\b[A-Z][a-z]{2} [A-Z][a-z]{2} [0-9]{1,2} [0-9][0-9]:[0-9][0-9]:[0-9][0-9] [0-9]{4} [-+][0-9]{4}\b', '<date>'),
    (r'\b[0-9]{4}-[0-9][0-9]-[0-9][0-9][ T][0-9][0-9]:[0-9][0-9](:[0-9][0-9])?( [-+][0-9]{4})?\b', '<date>'),
    (r'\b[0-9]+ (?:seconds?|minutes?|hours?|days?|weeks?|months?|years?) ago\b', '<date>'),
    (r'\b[0-9a-f]{7,40}\b', '<id>'),
    (r'\b[0-9]+(\.[0-9]+)? [KMG]?i?B(/s)?\b', '<size>'),
)]
_GIT_VERSION = re.compile(r'^git version ' + _DOT + r'*\Z')
_GIT_COUNT = re.compile('^' + _S + r'+([0-9]+)(?=' + _S + ')')


def git_normalize(text):
    """git-course: object ids, dates, temporary directories, sizes and the git version masked, `hint:` lines
    and blank lines dropped, `wc` count padding removed."""
    out = []
    for raw in _newlines(text).split('\n'):
        line = _rstrip_ws(ANSI.sub('', raw))
        if line.startswith('hint:'):
            continue
        for pattern, replacement in _GIT_RULES:
            line = pattern.sub(lambda _m, r=replacement: r, line)
        line = _GIT_DATE_LINE.sub(lambda m: m.group(1) + '<date>', line, count=1)
        for pattern, replacement in _GIT_REST:
            line = pattern.sub(lambda _m, r=replacement: r, line)
        line = _GIT_VERSION.sub('git version <version>', line, count=1)
        line = _GIT_COUNT.sub(lambda m: m.group(1), line, count=1)
        if line != '':
            out.append(line)
    return out


_PYTEST_TALLY = re.compile(
    r'^=*' + _S + r'*((?:[0-9]+(?:/[0-9]+)? (?:passed|failed|errors?|skipped|xfailed|xpassed|deselected|warnings?|rerun|tests? collected)'
    r'(?: \([0-9]+ deselected\))?(?:, )?)+|no tests ran)(?: in (?:[0-9.]+|TIME)s(?: \([0-9]+:[0-9][0-9]:[0-9][0-9]\))?)?'
    + _S + r'*=*\Z')
_PYTEST_ROW = re.compile('^(' + _NS + '+::' + _NS + '+?)' + _S + r'+(PASSED|FAILED|ERROR|SKIPPED|XFAIL|XPASS)\b', re.ASCII)
_PYTEST_SUMMARY_ROW = re.compile(r'^(FAILED|ERROR|XFAIL|XPASS|SKIPPED)' + _S + '+(' + _NS + '+::' + _NS + '+|' + _NS + r'+\.py)(?:' + _S + r'|\Z)')
_PYTEST_COLLECTED = re.compile(r'^(?:<[^>]+>' + _S + '*)*(' + _NS + r'+\.py::' + _NS + r'+)\Z')


def _pytest_outcome(text):
    tests = []
    seen = set()
    tally = None

    def add(item):
        if item not in seen:
            seen.add(item)
            tests.append(item)

    for raw in _newlines(text).split('\n'):
        line = _trim(ANSI.sub('', raw))
        row = _PYTEST_ROW.search(line)
        if row:
            add(f'{row.group(1)} {row.group(2)}')
            continue
        summary = _PYTEST_SUMMARY_ROW.search(line)
        if summary:
            add(f'{summary.group(2)} {summary.group(1)}')
            continue
        collected = _PYTEST_COLLECTED.search(line)
        if collected:
            add(f'{collected.group(1)} COLLECTED')
            continue
        m = _PYTEST_TALLY.search(line)
        if m:
            tally = ', '.join(p for p in m.group(1).split(', ') if not re.search(r'warnings?\Z', p))
    if tally is None:
        return None
    # JavaScript's default sort: by UTF-16 code units.
    return sorted(tests, key=lambda s: s.encode('utf-16-be')) + [f'tally: {tally}']


def _pytest_grade(stdout, stderr, expected_text):
    expected = _pytest_outcome(expected_text)
    actual = _pytest_outcome(stdout + stderr)
    if expected is None:
        return {'passed': False, 'diff': line_diff(stdout + stderr, expected_text)}
    diff = _diff(actual or [], expected)
    return {'passed': len(diff) == 0, 'diff': diff}


def _normalized_grade(normalize, stdout, stderr, expected_text):
    diff = _diff(normalize(stdout + stderr), normalize(expected_text))
    return {'passed': len(diff) == 0, 'diff': diff}


def grade_output(stdout, stderr, expected_text, grading='lines'):
    """Stdout alone first; when that differs, stdout then stderr under the courses' own rules."""
    if grading == 'ansible':
        return _normalized_grade(ansible_normalize, stdout, stderr, expected_text)
    if grading == 'terraform':
        return _normalized_grade(terraform_normalize, stdout, stderr, expected_text)
    if grading == 'dotnet':
        return _normalized_grade(dotnet_normalize, stdout, stderr, expected_text)
    if grading == 'git':
        return _normalized_grade(git_normalize, stdout, stderr, expected_text)
    if grading == 'bash':
        return _normalized_grade(bash_normalize, stdout, stderr, expected_text)
    if grading == 'pytest':
        return _pytest_grade(stdout, stderr, expected_text)
    stdout_diff = line_diff(stdout, expected_text)
    if not stdout_diff:
        return {'passed': True, 'diff': []}
    combined = stdout + stderr
    if grading == 'sql' and _sql_same_output(expected_text, combined):
        return {'passed': True, 'diff': []}
    if not stderr and grading != 'repl':
        return {'passed': False, 'diff': stdout_diff}
    if course_normalize(combined) == course_normalize(expected_text):
        return {'passed': True, 'diff': []}
    combined_diff = line_diff(combined, expected_text)
    return {'passed': False, 'diff': combined_diff if len(combined_diff) < len(stdout_diff) else stdout_diff}
